version: '3.8'

services:
  web:
    build:
      context: '.'
    image: book-manager
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - 3000:3000
    working_dir: /web
    volumes:
      - .:/web
      - ./bundle_cache:/bundle:rw,delegated
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432

  db:
    image: 'postgres:14.5-alpine'
    shm_size: 512mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/web/var/lib/postgresql/data,delegated
